### ISSUE TITLE
Escaping single quotes

### ISSUE THREAD

**Issue by vladfaust** [will/crystal-pg#103]
This code
```crystal
data = {
  "column" => "I'm good",
}

q = builder.table("table").insert(data)
Log.debug(q)
```
results in `INSERT INTO table (column) VALUES ('I\'m good')`, which will definitely not work with PostgreSQL :cry:

**Comment by bcardiff** [comment]
@vladfaust crystal-pg does not build sql statement. That is currently out of scope of crystal-db.

The issue you are experiencing is related to the shard that is providing that `builder`.
