### ISSUE TITLE
Hang on reading numeric[]

### ISSUE THREAD

**Issue by z64** [will/crystal-pg#105]
```cr
require "pg"

puts "Opening connection"
PG_DB = PG.connect("postgres://traikoa:traikoa@localhost")

puts "Creating table"
PG_DB.exec <<-SQL
CREATE TABLE IF NOT EXISTS array_test (
  position numeric[]
);
SQL

puts "Inserting values"
PG_DB.exec <<-SQL
INSERT INTO array_test (position) VALUES ('{0.1, 0.2, 0.3}');
SQL

puts "Running query"
PG_DB.query_one("select position from array_test") do |rs|
  puts rs
  puts rs.read(Array(Float64))
end

puts "Cleaning up"
PG_DB.exec <<-SQL
DROP TABLE array_test;
SQL

puts "Closing connection"
PG_DB.close
```
Yielding:
```
$ cr src/test.cr
Opening connection
Creating table
Inserting values
Running query
#<PG::ResultSet:0x559743c2acc0>
```
Where it will then hang indefinitely.

Switching to `float[]` or similar resolves the issue ; it seems to be specifically with `numeric[]`

Workaround for needing `numeric[]`-like type is to use `jsonb` instead and `#read(JSON::Any).to_a` and handle that.

Environment:
```
$ cr -v
Crystal 0.23.1 (2017-07-17) LLVM 4.0.1

$ shards
....
Using pg (cafe751c8dd33b988d57a2802506ac394cb84872)
...

$ pacman -Q postgresql
postgresql 9.6.3-3
```
Observe in above, I'm using `crystal-pg` master as I read about the fix from #100 / #98 

No clue where to look to fix this / debug it further :sweat_smile: 
If I can provide any other information / debugging, let me know.

---

I see that it's not listed as a supported array type ;
> array types: int8, int4, int2, float8, float4, bool, text

That said, it probably shouldn't be hanging anyways, or if support could be added that would be great 😄

**Comment by jwoertink** [comment]
Ok, turns out I'm getting this too. `rs.read(Array(Float64))` on this line [here](https://github.com/crystal-lang/crystal-db/blob/master/src/db/mapping.cr#L115) causes this to hang. I'm not sure how we can debug this though. @will any thoughts on how we could debug this? Since it just stops, it might have to be something lower I would imagine...

**Comment by asterite** [comment]
I might try to debug it tomorrow.

**Comment by jwoertink** [comment]
Thanks @asterite! I have a PR for [lucky](https://github.com/luckyframework/avram/pull/151) right now where I can recreate this if you need me to test anything.
