### ISSUE TITLE
move to crystal-lang repository

### ISSUE THREAD

**Issue by drujensen** [will/crystal-pg#106]
Would it be possible to move this to the `crystal-lang` repository?

  pg:
    github: will/crystal-pg

  mysql:
    github: crystal-lang/crystal-mysql

  sqlite3:
    github: crystal-lang/crystal-sqlite3

**Comment by bcardiff** [comment]
I don't the a concrete benefit on doing that. Quite the opposite. Like it is, it encourage others to build libraries since it's not that all need to be inside the crystal-lang organization. Crystal-db already links to this repo as the driver for pg. 

Also, from an historical perspective, will created it and did most of the job.

Why would you prefer it to be in crystal-lang org or what would you think it will come from it?

**Comment by drujensen** [comment]
I've found that people are less inclined to use an open source product (including myself) if they believe its not supported by more than just one individual. There is comfort in knowing that its an officially supported project and that it will not go away when Will decides that he doesn't want to support it anymore.

Moving it under the `crystal-lang` repository doesn't in anyway remove Will from being the main contributor.  Anyone that views the history or insights will see that. If anything it will encourage more developers to contribute since their project might become the officially recommended library by the crystal community.

**Comment by bcardiff** [comment]
will/crystal-pg is linked in the readme of crystal-db and in other docs. I would like to see that as a signal of support/appreciation of the shard that should encourage others to use it.

Regarding the project insight, crystal-pg has already more contributors than the other drivers actually.

I get the sense of safety if it's inside crystal-lang org. But I would like to see the community go beyond that.

If at any time will want to stop maintaining doing a transfer or a fork is an option, but I don't think there is an issue at the moment with the maintenance.

**Comment by drujensen** [comment]
I believe the crystal community is "beyond that" and that is exactly why I think it would be the right move.  I am absolutely appreciative of the contributions made by @will and in no way would I want that diminished by moving a repository.  I would hope this is not taken as if I don't appreciate any contribution made to the crystal community.  Hopefully you and @will will reconsider at some point.
