### ISSUE TITLE
Docrystal is abandoned

### ISSUE THREAD

**Issue by vladfaust** [will/crystal-pg#108]
https://github.com/docrystal they still use outdated Crystal version, so `crystal docs` doesn't work. It's a pity. I suggest using [Travis CI Push to GitHub pages functionality](https://docs.travis-ci.com/user/deployment/pages/).

But I believe that this issue will hang here for centuries. Crystal community is dead IMHO.

**Comment by will** [comment]
I've removed the link on the readme. The `crystal docs` command works locally.
