### ISSUE TITLE
Escaping Strings

### ISSUE THREAD

**Issue by ysbaddaden** [will/crystal-pg#11]
I just started out playing with crystal-pg, and I noticed that we can't escape strings and identifiers. Methods like `escaped = connection.escape_literal("string")` and `quoted = connection.escape_identifier(table_name)` for example.

http://www.postgresql.org/docs/current/static/libpq-exec.html#LIBPQ-EXEC-ESCAPE-STRING

**Comment by will** [comment]
If you use the parameterized form of exec, I don't believe it's necessary to use escape_literal

> Note that it is not necessary nor correct to do escaping when a data value is passed as a separate parameter in PQexecParams or its sibling routines.

But escape_identifier is probably useful. Maybe should just include both for completeness though.

**Comment by ysbaddaden** [comment]
Sometimes the params form is complicated to get working, and requires collecting values into a big union array or tuple, which is anything but fun in a static language. Injecting escaped values into the SQL String is just easier.

**Comment by will** [comment]
I added these two in https://github.com/will/crystal-pg/compare/cafec48cd656cc2a200060e5e23c09cda064c87c...cafee69 and released a new version 0.2.0

Thanks for the suggestion.
