### ISSUE TITLE
undefined method to_hash

### ISSUE THREAD

**Issue by extremety1989** [will/crystal-pg#117]
username@DESKTOP-VH5PTMF:/mnt/c/Users/andre/cr/space$ crystal run src/index.cr --error-trace
Error in src/index.cr:16: instantiating 'Note:Class#all(DB::Database)'

  socket.send Note.all(conn).to_json

  socket.send Note.all(conn).to_json
                   ^~~

in src/models/note.cr:12: instantiating 'Note:Class#transform_notes(DB::ExecResult)'

        self.transform_notes(conn.exec(%{
             ^~~~~~~~~~~~~~~

in src/models/note.cr:52: undefined method 'to_hash' for DB::ExecResult

        notes.to_hash.map do |note|
              ^~~~~~~

**Comment by crazycris80** [comment]
F

**Comment by will** [comment]
I'm not sure if this is an issue with the pg driver, but instead the db shard. Can you share a minimal reproducible code sample?

**Comment by extremety1989** [comment]
@will never mind, i used old docs..

**Comment by will** [comment]
Glad you figured it out :)
