### ISSUE TITLE
32 and 64bit byte endian swapping

### ISSUE THREAD

**Issue by will** [will/crystal-pg#12]
I'm working on using the binary interface instead of the text, and as part of this you need to switch endianness.

I've looked at 4 ways to do this, but I'm unsure which is the best. One (actually swapping things in memory) is gross, so that's off the table. The remaining 3 are
- use ntohl from libc. This will be a noop on like powerpcs, but does that even matter with crystal? It ends up turning into the llvm intrinsic anyway.
- use llvm intrinsic directly. This is already present in crystal unlike nothl
- do byte shifting manually. This appears to turn into optimized assembly due to the benchmark, but I haven't actually checked yet. This has the greatest visual similarity between 32 and 64 implementations (the nothl and intrinsic starts looking gross at 64bit).

https://gist.github.com/will/c348bf90a7cbd7e93fd0 has the implementations and benchmark code.

**Comment by will** [comment]
Also I wonder if these are generic enough to belong in Crystal itself? 32bit is fine enough perhaps with the Intrinsic, but it gets nasty for 64bit(cc @asterite)

**Comment by will** [comment]
went with manual shifting

**Comment by jsaak** [comment]
I do not understand why you went for manual bit shifting, this way your code only works on little-endian machines, right?

**Comment by will** [comment]
The data coming is from postgres is always little-endian. The host machine's endianiness is irrelevant with this approach.
