### ISSUE TITLE
Breaking changes in 0.24.1

### ISSUE THREAD

**Issue by greenbigfrog** [will/crystal-pg#120]
crystal-pg is broken as of right now.

https://github.com/will/crystal-pg/blob/22a6f1317b00195b4302d79b3b3d47b36c883099/src/pg/decoder.cr#L220
https://github.com/crystal-lang/crystal/pull/5022

**Comment by greenbigfrog** [comment]
```
in lib/pg/src/pg/decoder.cr:220: undefined method 'ticks' for Time

    JAN_1_2K_TICKS = Time.new(2000, 1, 1, kind: Time::Kind::Utc).ticks
                                                                 ^~~~~
```

**Comment by will** [comment]
Thanks, I was waiting for the release to push the fix, since it broke compatibility with older crystal versions. crystal-pg 0.14.0 has been released which fixes this.

**Comment by greenbigfrog** [comment]
:+1:
