### ISSUE TITLE
When postgres 9.3 was installed by apt, it doesn't work.

### ISSUE THREAD

**Issue by 8398a7** [will/crystal-pg#13]
```
/usr/bin/ld: /opt/crystal/bin/../embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
//lib/x86_64-linux-gnu/libcom_err.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

```crystal
require "pg"
DB = PG.connect("postgres://user@localhost:5432/db")
result = DB.exec({Int32}, "select count(id) from users")
p result
```

- ubuntu 14.04LTS
- postgres 9.3.9
- crystal 0.7.5

I want to know how to resolve this issue.

**Comment by will** [comment]
This looks similar to https://github.com/will/crystal-pg/issues/8 which is some sort of linking problem that we weren't able to get to the bottom of, unfortunately.

Just to make sure when you run `pg_config` all the values there are correct?

**Comment by 8398a7** [comment]
I tried some `pg_config` value, but there were not correct.

It ran correctly after to 9.4 the postgres.
Despite pass the test with postgres 9.3 in travis, I wonder.

**Comment by will** [comment]
The version of the server doesn't matter much as long as it's > 7.3 or so, the last time the protocol changed. 

What I think happened is there was something not quite right with your local postgres setup, if `pg_config` was giving the wrong information, and when you updated to 9.4 you fixed that as a side-effect.

This project uses `pg_config` to find the appropriate directories to link against.

**Comment by 8398a7** [comment]
I investigated the pg_config, there was a difference such as follows.

```
# postgres 9.3.9
INCLUDEDIR = /usr/include/postgresql
LIBDIR = /usr/lib
```

```
# postgres 9.4.4
INCLUDEDIR = /usr/include/postgresql
LIBDIR = /usr/lib/x86_64-linux-gnu
```

Therefore, I tried to rewrite the libpq.cr in this way with postgres 9.3.9, it was successful.

```crystal
module PG
  @[Link(ldflags: "-lpq -I`pg_config --includedir` -L /usr/lib/x86_64-linux-gnu")]
  lib LibPQ
```

My postgres was installed by apt, therefore what is better to take action as good think.
What do you think?

**Comment by will** [comment]
Did/do you have the `libpq-dev` package installed from apt?

**Comment by 8398a7** [comment]
Yes, I have.

**Comment by ysbaddaden** [comment]
I'm having this bug too, on a "clean" ubuntu trusty install. I never upgraded from another release and I only ever installed PostgreSQL 9.3 (but am up to date on updates and security).

The minimum snippet to reproduce is:
```crystal
require "pg"
PG.connect("postgres://postgres:@localhost/")
```

- it fails to compile with the official crystal DEB packages, which uses some embedded static libs (eg: libpcl.a, libgc.a, ...)
- it passes if I compiled crystal myself, which uses shared libraries (so static libs may be a hint)
- it passes with `crystal test_pg.cr --link-flags "-L/usr/lib/x86_64-linux-gnu"` (something seems required in that directory)

BTW: the `-I includedir` is unnecessary in the `@Link` definition since crystal doesn't care about headers files. Actually `@[Link("pq")]` is enough on Linux, except that we need the `-L/usr/lib/x86_64-linux-gnu`, even though libpq is installed in `/usr/lib`. Maybe libpq merely highlights a linking issue that is unrelated?

**Comment by ysbaddaden** [comment]
Errata: it passes with `-L/usr/lib/x86_64-linux-gnu` because the linker no longer uses the embedded static libs from `/opt/crystal/embedded/lib` and instead uses shared libs from `/usr/lib/x86_64-linux-gnu` to compile the binary.

**Comment by ysbaddaden** [comment]
Related (unsolved): http://stackoverflow.com/questions/13328144/end-symbol-disappears-when-linking-to-libcurl

**Comment by will** [comment]
Is `/usr/lib/x86_64-linux-gnu` not the result of `pg_config --libdir` for you?

If it is the same, then I don't understand why the `@[Link(ldflags: "-lpq -I`pg_config --includedir` -L`pg_config --libdir`")]` line doesn't work (even if -I isn't necessary). 

If it isn't the same, then I don't understand why your `pg_config` is returning incorrect data.

**Comment by ysbaddaden** [comment]
No, `pg_config --libdir` states `/usr/lib` which is where `libpq.{a,so}` is indeed installed.

This seems to be a common linker bug, triggered by linking against `libgc.a` and `libpq.so` or `libcom_err.so` but doesn't happen when using `libgc.so` (or something like that).

**Comment by will** [comment]
I checked with my Ubuntu-using colleges, and they have pg_config binaires that give the correct results
```
~$ pg_config --libdir
/usr/lib/x86_64-linux-gnu
```

Can you try something like 
```
export PATH=/opt/PostgreSQL/9.3/bin/:$PATH
```
(or wherever the binaries are) to get a proper pg_config?

**Comment by fdr** [comment]
Hi,

@will asked me to have a look at how `pg_config` presents `--libdir` on Ubuntu. It looks like it has a useful value on my system:

```sh
$ pg_config --libdir
/usr/lib/x86_64-linux-gnu
$ cat /etc/issue.net 
Ubuntu 15.04
```

**Comment by fdr** [comment]
I use the PGDG packages.

**Comment by will** [comment]
@fdr I've been able to reproduce this on an aws instance, and it also happens on the image b&p uses for slugc. I added your pubkey to the aws instance, can you help me track this down?

**Comment by will** [comment]
So, @fdr and I tracked this down more, https://github.com/manastech/crystal/issues/1269 

It explains why when the libdir isn't /usr/lib things work

**Comment by will** [comment]
The driver is now native, so this problem is no longer relevant.
