### ISSUE TITLE
Numeric.to_s is broken

### ISSUE THREAD

**Issue by greenbigfrog** [will/crystal-pg#133]
I've come across a case where the `#.to_s` is broken.
`        (0..weight).each { |idx| io << digits[idx].to_s }` [L 84](https://github.com/will/crystal-pg/blob/master/src/pg/numeric.cr#L84)

The number that's supposed/expected to be the result is ` 800000`
```
weight # => 1_i16
digits # => [80_i16]

Index out of bounds (IndexError)
  from /home/greenbigfrog/crystal/src/indexable.cr:53:17 in 'at'
  from /home/greenbigfrog/crystal/src/indexable.cr:73:5 in '[]'
  from lib/pg/src/pg/numeric.cr:87:48 in 'to_s'
  from /home/greenbigfrog/crystal/src/object.cr:96:7 in 'to_s'
```

**Comment by will** [comment]
Thanks!
