### ISSUE TITLE
Crystal next support

### ISSUE THREAD

**Issue by marksiemers** [will/crystal-pg#135]
While debugging something unrelated against crystal master, it looks like some upcoming breaking changes will need to be incorporated:

- Change from `kind: Time::Kind::Utc` to `location: Time::Location::UTC: https://github.com/crystal-lang/crystal/commit/f3168b6be999dc10e7b63fa2281e7d9265087609#diff-5169e17a6af0e17bcacc9d7129d337dcR236
- Change from `JSON::Type` to `JSON::Any`

**Comment by greenbigfrog** [comment]
Already opened a PR #131

**Comment by vladfaust** [comment]
Must be closed already.

**Comment by will** [comment]
Yeah this should have been closed when #131 was merged.
