### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by werner** [will/crystal-pg#14]
Hi, I'm trying to deploy an app in heroku using crystal-pg, but I have the next errors:

```
remote: -----> Compiling main.cr
remote: /usr/bin/ld: /tmp/crystal/bin/../embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
remote: //lib/x86_64-linux-gnu/libcom_err.so.2: error adding symbols: DSO missing from command line
remote: collect2: error: ld returned 1 exit status
remote: Error: execution of command failed with code: 1: `cc -o main "/tmp/build_9e3bf6082d648b8407cde8b368afff5c/.crystal/tmp/build_9e3bf6082d648b8407cde8b368afff5c/main.cr/main.o"   -lpq -I`pg_config --includedir` -L`pg_config --libdir` -lssl -levent -lrt -lpcl -lpcre -lm -lgc -lpthread -lunwind`
```

Do you have any idea how to solve it?. Thanks.

**Comment by will** [comment]
Well this is embarrassing as I work on the postgres team at heroku.

It seems the same as #13 which is still unsolved. If it is the same, what's happening is the linking step isn't returning the correct thing for `pg_config --libdir` so when it goes to link libpq it fails.

**Comment by will** [comment]
@fdr and I tracked this down more, https://github.com/manastech/crystal/issues/1269

**Comment by will** [comment]
https://github.com/zamith/heroku-buildpack-crystal/pull/2 might have fixed it, but we're stuck for a while due to https://github.com/manastech/omnibus-crystal/issues/2

**Comment by will** [comment]
The driver is now native, so this problem is no longer relevant.

**Comment by werner** [comment]
Awesome, thanks.
