### ISSUE TITLE
Error installing version 0.15.0 with Crystal 0.25.0 and Amber 0.8.0

### ISSUE THREAD

**Issue by lebogan** [will/crystal-pg#145]
I am using this shard with an amber project and keep getting this error:
```
Error resolving pg (~> 0.14.1, ~> 0.15.0)
```
My `shard.yml`:
```
  pg:
    github: will/crystal-pg
    version: ~> 0.15.0
```
If I try to install the master branch, I get 0.14.1 which breaks my app with JSON::TYPE error.

I think you fixed the JSON error. Do I have to install the latest version another way?

Thank you for this great shard.

**Comment by kostya** [comment]
may be this shards 0.8.0 bug, try `~/.cache/shards/`

**Comment by lebogan** [comment]
Thank you. Removing the cached repo and reinstalling did the trick.:-)
