### ISSUE TITLE
Works with scram-sha-256?

### ISSUE THREAD

**Issue by MrSorcus** [will/crystal-pg#154]
Subj.

**Comment by will** [comment]
Not yet, but scram is a feature that would be nice to have

**Comment by jkatz** [comment]
Hi!

There has been discussion on the PostgreSQL mailing list of making SCRAM-SHA-256 the [default password encryption method](https://www.postgresql.org/message-id/flat/efcbd7a2-f7fb-6788-6d7f-f627ac838d4c%402ndquadrant.com) starting with PostgreSQL 13 (which would be released roughly ~ September 2020).

Please let me know if I can help in any way. Thanks!

**Comment by will** [comment]
@jkatz if you know of any places that breaks down step-by-step the protocol for scram that'd be helpful.

**Comment by jkatz** [comment]
Hey @will!

The definitive source is here: https://tools.ietf.org/html/rfc5802#section-3
The definitive SCRAM-SHA-256 example is here: https://tools.ietf.org/html/rfc7677

I found this code helpful in understanding the client/server interactions: https://github.com/tlocke/scramp/blob/master/scramp/core.py

I've also been playing around with implementing the protocol in Python; I have one of the steps I'm happy with. I'm happy to work on a patch in Ruby (it's been awhile, but I could probably come up with something).

**Comment by will** [comment]
This isn't ruby though, but I'd love for you to submit patches ;)

The python link is helpful thanks!

Another thing, do you know if it's a lot different work to do the scram by itself and then to also do the channel binding?

**Comment by jkatz** [comment]
Thanks. I'll try to conjure up a patch :-)

The channel binding is specified as [part of SCRAM](https://tools.ietf.org/html/rfc5802#section-6), it's indicated by a parameter that is passed between client/server.

At present, PostgreSQL only supports [`tls-server-end-point`](https://tools.ietf.org/html/rfc5929#section-4) though AIUI it is not enforced (i.e. the client can request it, but the server cannot mandate it).

I don't think it would be too difficult to add on, if not get the main SCRAM-SHA-256 in first and then do an iteration with channel binding. A bunch of the implementations I've seen explicitly do not set the channel binding options.

**Comment by will** [comment]
I have scram working in a branch, but fighting with CI so it hasn't landed yet.

**Comment by jkatz** [comment]
Awesome! I had it 60% implemented a few months back, but then got distracted, and I’m sure what you did is way better than what I did.

That said, I know enough Crystal now that I can review it when you’re ready!
