### ISSUE TITLE
Trying to read a empty array causes infinite hang/sleep

### ISSUE THREAD

**Issue by greenbigfrog** [will/crystal-pg#157]
When trying to read/map a array but receiving a empty cell (`null`), it'll just hang endless instead of simply raising a exception.
```cr
require "pg"

DATA = PG.connect(ENV["POSTGRES"])

DATA.exec("DROP TABLE IF EXISTS test;")
DATA.exec("CREATE TABLE test (text_array text[]);")

struct Test
  DB.mapping(
    text_array: Array(String)
  )
end

DATA.exec(<<-SQL)
    INSERT INTO test(text_array) VALUES ('{"hi", "hey"}');
SQL

def query
  DATA.query_all("SELECT * FROM test", as: Test)
end

pp query

DATA.exec("INSERT INTO test VALUES ('{}');")

pp query

DATA.exec("INSERT INTO test VALUES (null);")

# When trying to query now, it'll simply hang infinite
pp query
```

Making it nil-able, gets rid of the error of course. 
```cr
DB.mapping(
    text_array: Array(String)?
)
```

I wasn't sure if this was a crystal-pg or crystal-db issue, but figured more likely crystal-pg.

**Comment by straight-shoota** [comment]
Reduced to:
```cr
DB.open(ENV["DATABASE_URL"]) do |db|
  db.query_one("SELECT NULL", as: Array(String))
end
```

Declaring a different expected type than `Array` (for example `db.query_one("SELECT NULL", as: String)`) raises an appropriate exception: `PG::ResultSet#read returned a Nil. A String was expected.`

**Comment by asterite** [comment]
This works fine in `master`. I think this can be closed.
