### ISSUE TITLE
UNIX sockets

### ISSUE THREAD

**Issue by remydev** [will/crystal-pg#168]
Hello,

The documentation does not mention how to connect to postgres through UNIX sockets. Is that currently possible?

Cheers,

**Comment by will** [comment]
Yes, if the host starts with a `/` it's assumed to be a unix socket 

https://github.com/will/crystal-pg/blob/1548bb2552104241a8b020869f1a64c9744cfe44/src/pq/conninfo.cr#L9

**Comment by straight-shoota** [comment]
That means relative paths are not supported?
