### ISSUE TITLE
How to get count(*) value from a SQL request ? 

### ISSUE THREAD

**Issue by solisoft** [will/crystal-pg#17]
I'm trying to get value from a very basic command : 

    SELECT COUNT(*) FROM users

but rows always return [[0]] (even when I have some lines on my table)

So for now I just do a "SELECT id FROM users" and I check row length

**Comment by will** [comment]
The return type for count(*) is bigint, which was broken. Thanks for the report

**Comment by mang** [comment]
Hi, I have the same problem still. Was this ever fixed? Or is there a way around it?

**Comment by RX14** [comment]
This works, the correct type is `Int64`

**Comment by mang** [comment]
Oh, thanks a lot, that works:)
