### ISSUE TITLE
update to crystal-db 0.8.0

### ISSUE THREAD

**Issue by petr-fischer** [will/crystal-pg#198]
Hello, crystal-pg need to be updated to crystal-db 0.8.0 (https://github.com/crystal-lang/crystal-db).

Now, it's impossible to use crystal-pg and crystal-mysql in one project, because crystal-mysql depends on crystal-db 0.8.0 and crystal-pg depends on crystal-db 0.7.0.

**Comment by straight-shoota** [comment]
There is already a PR for that: #197

You definitely *can* use pg and mysql in the same project. You just need to pin `crystal-mysql` to version 0.9.0.

**Comment by petr-fischer** [comment]
Duplicate of #197
