### ISSUE TITLE
can't find file 'crypto/md5' Using pg (0.11.0)

### ISSUE THREAD

**Issue by scriptmaster** [will/crystal-pg#214]
```
Using pg (0.11.0)

# crystal build postgres.cr 
Showing last frame. Use --error-trace for full trace.

In lib/pg/src/pq/connection.cr:2:1

 2 | require "crypto/md5"
     ^
Error: can't find file 'crypto/md5'
```

**Comment by bcardiff** [comment]
You are using an updated crystal but an outdated crystal-pg.

Current crystal-pg is 0.21.1. 

The rename from Crypto::MD5 to Digest::MD5 happened in crystal 0.21.0 and was crystal-pg 0.13.2 has already updated with it.
