### ISSUE TITLE
Error: no overload matches 'PG::Decoders.array_decoder' with type UUID.class

### ISSUE THREAD

**Issue by jwoertink** [will/crystal-pg#224]
The `PG::Decoders.array_decoder` method supports a lot of the types that postgres supports, but doesn't include `UUID`.

I'm using `version: 0.22.1`

**Comment by matthewmcgarvey** [comment]
Looks like it's just a matter of add UUID to this list https://github.com/will/crystal-pg/blob/cafe0fd89eeb68cd579f539da44b89afcd51a21f/src/pg/decoders/array_decoder.cr#L112
