### ISSUE TITLE
Connecting to unix socket with url

### ISSUE THREAD

**Issue by tleydxdy** [will/crystal-pg#227]
I tried various forms such as
```
postgres://user:pass@/dbname
postgres://user:pass@/dbname?host=/var/run/postgresql
postgres://user:pass@%2Fvar%2Frun%2Fpostgresql/dbname
```
but they all doesn't seem to work

**Comment by will** [comment]
Hm, it might not be currently possible with a url.

The relevant code is here: https://github.com/will/crystal-pg/blob/master/src/pq/conninfo.cr#L52

This will use a socket if the `host` parameter starts with a `/` character. However the crystal stdlib `URI.parse` might make it impossible to get a host starting with that. I'm unsure what can be done about this.

As an alternative, you should be able to do `"host=/var/run/postgresql user=user password=password"` or with a bit more effort construct a `PQ::ConnInfo` directly.

**Comment by tleydxdy** [comment]
yeah, I'm using someone else's code, I will see what I can do.

**Comment by tleydxdy** [comment]
aha, `postgres://user:pass@/dbname?host=/var/run/postgresql` worked, I just made some silly mistake. :(
