### ISSUE TITLE
Connection Pool

### ISSUE THREAD

**Issue by kbrock** [will/crystal-pg#23]
Hello,

When putting this into a webapp, do you put a connection pool around this?

Thanks,
Keenan

**Comment by will** [comment]
A connection pool is a good idea. I'm not sure if a pool makes sense to do
at the driver level or not.

**Comment by ysbaddaden** [comment]
I don't think the driver should bother about a pool. I think it's a generic structure.

**Comment by kbrock** [comment]
agree it doesn't belong in this driver. is there already one out there in crystal land?

**Comment by ysbaddaden** [comment]
There is mine: https://github.com/ysbaddaden/pool/ (still rough)

**Comment by qio-io** [comment]
Anything against using PgBouncer?

**Comment by qio-io** [comment]
@ysbaddaden , i tested pool and i'm using it with `crystal-redis and crystal-pg` shards. Excellent work and it definitely increased the ips of my app.

**Comment by sdogruyol** [comment]
I'm also using [Pool](https://github.com/ysbaddaden/pool) for [kemal-pg](https://github.com/sdogruyol/kemal-pg) and [kemal-mysql](https://github.com/sdogruyol/kemal-mysql). It's really great so far. Thanks @ysbaddaden
