### ISSUE TITLE
Tiny change needed for Crystal 0.9 support

### ISSUE THREAD

**Issue by sardaukar** [will/crystal-pg#26]
This line requires a space after the *y* in ```query``` :D 

```
Syntax error in ./libs/postgresql/pg/connection.cr:29: space required before colon in type restriction

    def exec_all(query: String)
```

**Comment by sardaukar** [comment]
Didn't think forking was warranted for this

**Comment by jhass** [comment]
8fae0a05169f62f48f27393fe5796985a72047c6 fixed this as a drive by, it's just not released yet. You can use `branch: master` in your `shard.yml` in the meantime.

**Comment by will** [comment]
I just released a new version, so you should be good to go @sardaukar if you didn't already go to `branch: master`

**Comment by sardaukar** [comment]
Thanks!
