### ISSUE TITLE
No such table

### ISSUE THREAD

**Issue by waghanza** [will/crystal-pg#33]
Hi,

When I try to execute an sql query on the wrong table, I have a raw error from `PQ` driver, but no

~~~crystal
error.status
~~~
Is it a wanted behavior ?

Regards,

PS : Rather ask before **PR**

**Comment by will** [comment]
Thanks for checking out this project and for the issue.

It looks like it is setting the status, but there isn't any way to access it. If you reopen the error class and add a `getter` it works. Is that what you were talking about?

```
require "pg"

class PG::ResultError
  getter status
end

DB = PG.connect("postgres:///")
begin
  DB.exec("select * from whatever")
rescue e : PG::ResultError
  p e.status # => PGRES_FATAL_ERROR
end
```

**Comment by will** [comment]
Please feel free to reopen this if you're still having problems
