### ISSUE TITLE
Exception when requesting `rows` of empty resultset

### ISSUE THREAD

**Issue by spalladino** [will/crystal-pg#38]
On version 0.7.0: Given an empty resultset, invoking `result.rows` yields `this should be unreachable`. For example:

```crystal
p db.exec("SELECT * FROM mytable where 1=0" ).rows
```

**Comment by asterite** [comment]
The problem seems to be [this](https://github.com/will/crystal-pg/blob/master/src/pg/result.cr#L22):

```crystal
    def rows
      a = [first]
      each(@types) { |r| a << r }
      a[1..-1]
    end
```

I think this can be implemented like this:

```crystal
    def rows
      a = [] of typeof(first)
      each(@types) { |r| a << r }
      a
    end
```

@spalladino You can try redefining `Result#rows` in your project and see if that works.

**Comment by spalladino** [comment]
That works, thanks @asterite! By the way, I was checking this with @waj, and he arrived at **exactly** the same code as you did.

**Comment by will** [comment]
Thanks @spalladino for reporting, and @asterite for the fix :)
