### ISSUE TITLE
Support for arrays?

### ISSUE THREAD

**Issue by raydf** [will/crystal-pg#54]
Hello Will:

Is there any support for arrays types?. I couldn't find in docs.
https://www.postgresql.org/docs/9.1/static/arrays.html

Rayner

**Comment by will** [comment]
There isn't support for it yet. I just took a stab at adding it, but the binary representation is [a bit more complex ](https://github.com/postgres/postgres/blob/3aff33aa687e47d52f453892498b30ac98a296af/src/backend/utils/adt/arrayfuncs.c#L1591-L1631) than I originally figured, so it'll be a bit before I can add support. 

I'm pasting in a chat log from irc here just for my own notes:

```
4:53 PM W<willl> will 
what does does the lbound int in the header signify in the binary representation of arrays?

4:53 PM R<RhodiumToad> 
lower bound of the dimension
4:54 PM by default this is 1, but arrays can have arbitrary bounds

4:54 PM W<willl> will 
thanks, is there an easy way to generate an example array where it's not 1?

4:55 PM R<RhodiumToad> 
select ('[10:12]={1,2,3}'::integer[])[10];

4:55 PM W<willl> will 
RhodiumToad: perfect, thank you

4:55 PM R<RhodiumToad> 
note that the lower bound can be zero or negative, too
```

**Comment by raydf** [comment]
Will:

Thanks for the response, i used a string for conversion at runtime '{..}', as always kudos for an amazing shard, very appreciated.

**Comment by will** [comment]
Hey an update, I started on this a bit ago but things got a bit busy. Just figured out how to get all the different arrays ( https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.h#L448-L488 ) with some fancy 3 type generic dancing. Still needs some polish and the rest of the types, but should be easier going now https://github.com/will/crystal-pg/pull/57

**Comment by will** [comment]
v0.10.0 has support for int8, int4, int2, float8, float4, bool, and text arrays. There are a ton more but I think these are the most useful.
