### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [will/crystal-pg#6]
I tried to write some stuff and broke it: 

```console
maciek@mothra:~/code/aux/crystal-pg$ crystal spec
Segmentation fault (core dumped)
Program terminated abnormally with error code: 35584
```

See https://github.com/uhoh-itsmaciek/crystal-pg/commit/4da9d4072a96e81fce5ff96b697a3ef4a8be25e3

**Comment by will** [comment]
one of the constants was made a global variable outside of the one you intended to change. So it was nil, and that caused a segfault. I made it nil can't make it in anymore goodbye nil

**Comment by will** [comment]
The error you'd get now if you tried it would be 
```
no overload matches 'PG::Connection#initialize' with types Nil
Overloads are:
 - PG::Connection#initialize(conninfo : String)
```
