### ISSUE TITLE
Encode time values correctly when inserting into the database

### ISSUE THREAD

**Issue by RX14** [will/crystal-pg#61]
At the moment time values are inserted using their string representations which only have single-second precision. As postgres supports microsecond-level precision, this is a bit strange.

**Comment by will** [comment]
This'll be the 3rd or 4th special-cased encoder, so probably need to actually go to some sort of interface for that instead of a switch this time.

**Comment by will** [comment]
It looks like Crystal's `Time::Formatter` only supports microseconds with `%L`. Does cafe9047542b8bf30a6bb22f99fd9a0c82323a0c solve your issue?

**Comment by RX14** [comment]
@will Sorry for the late reply, this does indeed appear to fix it!

![](https://aww.moe/c73v1i.png)

**Comment by benoist** [comment]
Can this be closed, or is there stil an issue?
