### ISSUE TITLE
Undefined method 'to_hash' for DB::ExecResult

### ISSUE THREAD

**Issue by bthachdev** [will/crystal-pg#65]
This only happens with version 0.12.0

**Comment by will** [comment]
v0.12 was a big change (#60) to use the crystal-db api. I haven't yet updated the readme, but probably a lot of things don’t work the same way.

**Comment by raydf** [comment]
You can use crystal-db api #query_all. In this docs https://crystal-lang.org/docs/database/index.html, you can see the method #query_one that has a similar syntax to query_all with the :as named parameter.

**Comment by bthachdev** [comment]
Thanks raydf, I will check it. 
Now I have a web app using crystal-pg 0.11, so change to a new version will take a while.

**Comment by will** [comment]
I think this is answered, so I'm going to close it. Feel free to reopen though if not.
