### ISSUE TITLE
Undefined method 'empty' when exec is called without params

### ISSUE THREAD

**Issue by raydf** [will/crystal-pg#73]
Hello:

I'm receiving this error:

```bash 
undefined method 'empty' for Slice(Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil):Class
      perform_exec_and_release(Slice(Any).empty)
```

Code:

```crystal
DB.open("postgres:///") do |db| 
  db.exec("DROP SCHEMA IF EXISTS test CASCADE;")
end
```

Workaround:

```crystal
module DB
  abstract class Statement
    # See `QueryMethods#exec`
    def exec
      perform_exec_and_release([] of DB::Any)
    end
  end
end
```

I really don't know if is related to crystal-pg or also affect all crystal-db drivers. 

CC: @bcardiff.

**Comment by will** [comment]
Are you on Crystal >= 2.20.1? `Slice#empty` was added then https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md#0201-05-12-2016

**Comment by bcardiff** [comment]
Slice.empty was added in crystal 0.20.1 it's probably an outdated crystal version this issue.

**Comment by raydf** [comment]
That's correct. There's an outdated brew formula (current: 0.20.0)
http://brewformulas.org/CrystalLang.
I'll compile crystal from the master repo.

**Comment by raydf** [comment]
Thanks :).
