### ISSUE TITLE
Statement params support? (crystal-db)

### ISSUE THREAD

**Issue by samueleaton** [will/crystal-pg#77]
With the recent crystal-db convergence, are we able to do prepared statements with the `?` as seen in the second example in the ["Exec" section](https://crystal-lang.org/docs/database/#exec).

I'm getting `syntax error at or near "," (PQ::PQError)` if I try to use them.

**Comment by bcardiff** [comment]
Postgress use $1, $2, etc as stated in the crystal-db readme. And yes, they do work. 

Using params is a separate feature w.r.t. prepared statemtes, FWIW.

**Comment by will** [comment]
@samueleaton does using $1 $2 solve your problem?
@bcardiff would it make sense to call out that difference in those docs?

**Comment by samueleaton** [comment]
I will check if it fixes it for me when I get off work.
I'll try to do a PR for the docs to make a note of the difference that doc page I referenced.

**Comment by bcardiff** [comment]
a note was added in crystal-db/readme.md . But yes, a note in docs should be handy.
