### ISSUE TITLE
Dependency problem with pg 0.13.2

### ISSUE THREAD

**Issue by nobilik** [will/crystal-pg#82]
Hi, here is the output:
```
require "pg"
^
in lib/pg/src/pg.cr:2: while requiring "./pg/*"
require "./pg/*"
^
in lib/pg/src/pg/connection.cr:1: while requiring "../pq/*"
require "../pq/*"
^
in lib/pg/src/pq/connection.cr:2: while requiring "digest/md5": can't find file 'digest/md5' relative to '/.../lib/pg/src/pq'
require "digest/md5"
```

**Comment by will** [comment]
The newest version of pg requires the newest version of crystal. They
renamed the stdlib md5 package. It looks like you're on an older version of
crystal?

**Comment by will** [comment]
https://github.com/will/crystal-pg/pull/80

**Comment by benoist** [comment]
Can this be closed?

**Comment by will** [comment]
Yeah I think so, I was waiting for a response, but I think it's not an issue for this project.

**Comment by nobilik** [comment]
Yes, sorry. It wasn't an issue.
