### ISSUE TITLE
Failure on empty query spec

### ISSUE THREAD

**Issue by waghanza** [will/crystal-pg#84]
Hi,
I'm trying to test auth connections.

I have done this on https://travis-ci.org/waghanza/crystal-pg/jobs/207417066.

However I have error on travis (`ubuntu`) but not on my development machine (`fedora`).

Could a guru explain me this behavior ?

**Comment by will** [comment]
Can you try changing the URL to drop the localhost, like
postgres://postgres@/ then it'll connect over unix sockets instead of tcp.
Seems like something is wrong with the ssl setup like maybe Postgres isn't
compiled with ssl support.

**Comment by will** [comment]
It seems like the newer version of ubuntu exposes this, and until https://travis-ci.org/will/crystal-pg/builds/209479595 , this was using a previous ubuntu version. I'm unsure why that change exposes this behavior.
