### ISSUE TITLE
Testing with PG 9.5 ?

### ISSUE THREAD

**Issue by waghanza** [will/crystal-pg#85]
Hello,

I can see in the `README` and **travis config** that `crystal-pg` is tested on `PostgreSQL` 9.1 to 9.4.

I think that testing on `PostgreSQL` `9.6` (or `9.5`) **could** be great and `travis support this https://docs.travis-ci.com/user/database-setup/#PostgreSQL.

@will What do you think about that ?

PS : And probably it's a good idea to explicitly enable `postgis` on travis

**Comment by will** [comment]
Thanks, I didn't know travis finally added support for > 9.4 postgres. I tried putting it on in https://travis-ci.org/will/crystal-pg/builds/209479595 but ran into the same problem as #84 after upgrading to a later ubuntu release, which I'm not sure why that'd happen.

**Comment by waghanza** [comment]
@will The problem seems to come from environment type => vm or container based.

on the container base environment, I have a 

~~~crystal
type "line" not yet implemented
~~~

and I have the same error using `Docker` with **postgresql** `9.3` but not `> 9.4`

**Comment by waghanza** [comment]
fixed => https://github.com/will/crystal-pg/pull/86

PS : `line` datatype is not implemented in `postgresql` <9.4 (the test were successful but used the wrong pg libs versions)
