### ISSUE TITLE
Decoding types with unstable OIDs

### ISSUE THREAD

**Issue by bjeanes** [will/crystal-pg#88]
Hi @will (hope you're well!)

I'm working on a Crystal side-project at the moment that uses `crystal-pg`. It's working with a legacy database which has an eclectic mix of types that would have different OIDs from DB to DB and thus can't have statically defined decoders, as `crystal-pg` does.

I'm thinking of course of `citext`, `hstore`, and, in my case anyway, custom `DOMAIN`s based on other types.

I've been looking through the source code for `crystal-pg` (very readable, btw) and it occurs to me that to support something like `hstore`, the decoder map would have to be built up on a per-connection basis (vs globally) by querying `pg_type` et al as [Ruby's PG gem does](https://bitbucket.org/ged/ruby-pg/src/8a15026cfe7792eb1aff5cb77fefe109e8dbf6aa/lib/pg/basic_type_mapping.rb?at=default&fileviewer=file-view-default#basic_type_mapping.rb-106:107).

I've not played with the `pg_type` table much, but I wonder if the [`typcategory` column](https://www.postgresql.org/docs/8.4/static/catalog-pg-type.html#CATALOG-TYPCATEGORY-TABLE) could be used as a hint for a fallback decoder to use where a specialised one wasn't available. That might allow `citext` (or for e.g. an `DOMAIN` "`email`" based on `citext`) to naturally be decoded as would `text`.

I whipped up a query to get familiar with what the types in my DB looked like and the relationships between them, and I think something like this could work.

Query:

``` sql
WITH

categories(typcategory, category) AS (
  VALUES
    ('A', 'Array')
  , ('B', 'Boolean')
  , ('C', 'Composite')
  , ('D', 'Date/time')
  , ('E', 'Enum')
  , ('G', 'Geometric')
  , ('I', 'Network address')
  , ('N', 'Numeric')
  , ('P', 'Pseudo-types')
  , ('S', 'String')
  , ('T', 'Timespan')
  , ('U', 'User-defined')
  , ('V', 'Bit-string')
  , ('X', 'unknown')
),

types AS (
  SELECT
                                        oid
  , typtype                             "type"
  , typnamespace                        namespace_oid
  , typnamespace::regnamespace          namespace
  , typname                             "name"
  , typcategory                         category
  , (typcategory || ' - ' || category)  category_name
  , typbasetype                         base_oid
  , typelem                             element_oid
  , typarray                            array_oid
  , typdelim                            array_delimeter
  FROM pg_type JOIN categories USING (typcategory)
  WHERE typisdefined = 't'
)

SELECT
  types.oid
, types.namespace
, types.name
, types.category_name
, CASE WHEN base.oid    IS NOT NULL THEN (base.oid,    base.namespace,    base.name,    base.category)    ELSE NULL END base
, CASE WHEN element.oid IS NOT NULL THEN (element.oid, element.namespace, element.name, element.category) ELSE NULL END element
, CASE WHEN "array".oid IS NOT NULL THEN ("array".oid, "array".namespace, "array".name)                   ELSE NULL END "array"
FROM types
  LEFT JOIN types base    ON types.base_oid    = base.oid
  LEFT JOIN types element ON types.element_oid = element.oid
  LEFT JOIN types "array" ON types.array_oid   = "array".oid
WHERE types.type IN ('b', 'd');

```

I think there's enough information here to derive some types and it can be used to locate the OIDs of types with dedicated decoders, like `hstore`s.

Alternatively, upon encountering a value with unknown `oid`, a `SELECT $1::oid::regtype;` could be run to try resolve it to a known name and use that to map to a decoder.

Either way, it would still have to build up the OID mapping on a per-connection basis.

It's late here so the above might be a bit rambly. I'm going to keep thinking about this but I was just curious if there has been other discussion already about handling more types.

**Comment by bjeanes** [comment]
To elaborate on why this should be per-connection... I'm connecting to more than one DB in the same process and they have different OIDs for the same logical types. Just in case the reasoning here wasn't clear.

**Comment by bjeanes** [comment]
Closing in lieu of #89, for now.

**Comment by will** [comment]
Yeah, it for sure has to be per connection, since the oids for the extension types changes from database to database. Thanks for looking into this, it's one of the few things that, to my mind, was keeping from the a 1.0 release. I'll take look at 89.
