### ISSUE TITLE
Index out of bounds for empty resultset

### ISSUE THREAD

**Issue by Sdogruyol** [will/crystal-pg#9]
When trying to access the first row an empty result like below

```crystal
results = DB.exec("SELECT * FROM persons") # Empty resultset

pp results.rows.first
```

The program terminates itself because of error
     
  Index out of bounds (IndexOutOfBounds)

Theoritically this is OK. But we can't know if the table is empty or not beforehand. 

What do you think about this?

**Comment by will** [comment]
You can use Crystal's `first?` method if you want to optionally have nil in this case.
You can also pass a block to `first` and the result of the block is used instead if there is no element. `#first?` is implemented as `first { nil }`
You can also check if rows is `empty?`

``` crystal 
res = DB.exec("select * from dots where id=10000")
pp res.rows.size
pp res.rows.first?
pp res.rows.first { "anything" }
pp res.rows.empty?
```
```
res.rows.size = 0
res.rows.first? = nil
res.rows.first do
  "anything"
end = "anything"
res.rows.empty? = true
```
