### ISSUE TITLE
PQ(T) is not a module, it's a generic class

### ISSUE THREAD

**Issue by baelter** [will/crystal-pg#90]
```Error in src/app.cr:6: while requiring "pg"

require "pg"
^

in lib/pg/src/pg.cr:2: while requiring "./pg/*"

require "./pg/*"
^

in lib/pg/src/pg/connection.cr:1: while requiring "../pq/*"

require "../pq/*"
^

in lib/pg/src/pq/connection.cr:10: PQ(T) is not a module, it's a generic class

module PQ
       ^
```

```
crystal --version
Crystal 0.21.1 (2017-03-14) LLVM 4.0.0
```

Running MacOS 10.12.4
Installed crystal via brew

**Comment by bcardiff** [comment]
@baelter could be the case that you have other shards or file required that are declaring a `PQ(T)` class? That might be causing some class / module collision.

**Comment by baelter** [comment]
Oh yeah, collision with amqp. You (and amqp) should namespace your modules.

**Comment by bcardiff** [comment]
amqp datanoise/amqp.cr defines `::AMQP::PQ(T)` and will/crystal-pg `::PQ`, if you haven `include AMQP` somewhere I think you could remove it at you should be able to move forward.

**Comment by baelter** [comment]
Yeah they were fast in fixing it :) https://github.com/datanoise/amqp.cr/issues/13#issuecomment-292965116
Thanks for quick response here to 👍
